import React from 'react';
// import "./style.css";

const AboutUs = () => {
  return (
    <div className="container" style={{textAlign: "justify"}}>
        <p className='textCenter fs-6'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia non perferendis laborum quibusdam ab quisquam exercitationem voluptate sunt? Quae maiores, maxime dolorum consequuntur perspiciatis sit quas. Quos quidem ab, vel ratione sequi porro est. Dolor natus doloremque corrupti nihil saepe est eveniet quam! Velit consequuntur culpa asperiores voluptatibus, non quibusdam labore vel a? Nisi eveniet voluptatum aspernatur blanditiis numquam explicabo, modi praesentium aliquam consectetur illum placeat? Natus modi ipsam, ipsum itaque sint tempore laboriosam veniam cum? Dignissimos dolorum sequi unde voluptate, sapiente omnis quos, velit sint quod saepe voluptatem inventore, ipsam illo! Quidem quo eaque modi vitae, deserunt ea nam, nisi, necessitatibus unde placeat dolores magnam quam pariatur libero voluptatem tempora deleniti dicta. Maxime et optio omnis autem id eos amet quia nemo veniam libero! Dignissimos magnam, soluta corrupti laborum repellendus nobis aliquid quia voluptatibus labore culpa architecto eaque officia necessitatibus, itaque natus quam minima molestiae animi iusto? Minima esse tempora debitis porro pariatur recusandae ab atque quas iure tempore. Quidem deleniti fuga qui maxime architecto optio ducimus iste id? Perferendis doloribus hic ullam accusantium reprehenderit? Asperiores, nihil enim deserunt sint expedita commodi at optio, cupiditate quis eligendi illum. Eaque perferendis quaerat porro doloribus nulla veritatis obcaecati officiis sunt voluptatem beatae deleniti aspernatur eveniet dolores sapiente dolorum, eum, fugit expedita reprehenderit alias vel magni. Eos sit eligendi exercitationem est suscipit vitae sint placeat culpa nesciunt molestias dolor impedit laudantium ipsum alias veniam deleniti dicta eveniet, harum tempore quas eum! Dignissimos hic autem animi officiis tenetur aliquam quasi officia suscipit natus quis! Quas officia quibusdam laudantium ducimus eum! Et laboriosam nesciunt sequi eaque culpa, distinctio veniam. Rerum eum numquam, libero suscipit accusantium et labore laudantium cum tenetur doloribus sit placeat expedita dolor molestias iste odio repellendus incidunt culpa repellat quisquam alias amet deserunt. Itaque, vel magnam voluptatem assumenda quasi illum atque.</p>
    </div>
  )
}

export default AboutUs